In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/nehalbirla/motorcycle-dataset/BIKE DETAILS.csv

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv("/kaggle/input/datasets/nehalbirla/motorcycle-dataset/BIKE DETAILS.csv")

In [4]:
df.head()

,name,selling_price,year,seller_type,owner,km_driven,ex_showroom_price
0,Royal Enfield Classic 350,175000,2019,Individual,1st owner,350,NaN
1,Honda Dio,45000,2017,Individual,1st owner,5650,NaN
2,Royal Enfield Classic Gunmetal Grey,150000,2018,Individual,1st owner,12000,148114.0
3,Yamaha Fazer FI V 2.0 [2016-2018],65000,2015,Individual,1st owner,23000,89643.0
4,Yamaha SZ [2013-2014],20000,2011,Individual,2nd owner,21000,NaN

In [5]:
df.shape

(1061, 7)

In [6]:
df.isnull().sum()

name                   0
selling_price          0
year                   0
seller_type            0
owner                  0
km_driven              0
ex_showroom_price    435
dtype: int64

In [7]:
df.dropna(subset=['ex_showroom_price'],inplace=True)

In [8]:
df.head()

,name,selling_price,year,seller_type,owner,km_driven,ex_showroom_price
2,Royal Enfield Classic Gunmetal Grey,150000,2018,Individual,1st owner,12000,148114.0
3,Yamaha Fazer FI V 2.0 [2016-2018],65000,2015,Individual,1st owner,23000,89643.0
5,Honda CB Twister,18000,2010,Individual,1st owner,60000,53857.0
6,Honda CB Hornet 160R,78500,2018,Individual,1st owner,17000,87719.0
9,Bajaj Discover 125,50000,2016,Individual,1st owner,42000,60122.0

In [9]:
df.shape

(626, 7)

In [10]:
df.describe()

       selling_price         year      km_driven  ex_showroom_price
count     626.000000   626.000000     626.000000       6.260000e+02
mean    59445.164537  2014.800319   32671.576677       8.795871e+04
std     59904.350888     3.018885   45479.661039       7.749659e+04
min      6000.000000  2001.000000     380.000000       3.049000e+04
25%     30000.000000  2013.000000   13031.250000       5.485200e+04
50%     45000.000000  2015.000000   25000.000000       7.275250e+04
75%     65000.000000  2017.000000   40000.000000       8.703150e+04
max    760000.000000  2020.000000  585659.000000       1.278000e+06

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
le=LabelEncoder()

In [13]:
df['seller_type']=le.fit_transform(df['seller_type'])

In [14]:
df['owner']=le.fit_transform(df['owner'])

In [15]:
df.head()

,name,selling_price,year,seller_type,owner,km_driven,ex_showroom_price
2,Royal Enfield Classic Gunmetal Grey,150000,2018,1,0,12000,148114.0
3,Yamaha Fazer FI V 2.0 [2016-2018],65000,2015,1,0,23000,89643.0
5,Honda CB Twister,18000,2010,1,0,60000,53857.0
6,Honda CB Hornet 160R,78500,2018,1,0,17000,87719.0
9,Bajaj Discover 125,50000,2016,1,0,42000,60122.0

In [16]:
df['brand']=df['name'].str.split().str.get(0)

In [17]:
df['brand']=le.fit_transform(df['brand'])

In [18]:
df.head()

,name,selling_price,year,seller_type,owner,km_driven,ex_showroom_price,brand
2,Royal Enfield Classic Gunmetal Grey,150000,2018,1,0,12000,148114.0,11
3,Yamaha Fazer FI V 2.0 [2016-2018],65000,2015,1,0,23000,89643.0,16
5,Honda CB Twister,18000,2010,1,0,60000,53857.0,6
6,Honda CB Hornet 160R,78500,2018,1,0,17000,87719.0,6
9,Bajaj Discover 125,50000,2016,1,0,42000,60122.0,2

In [19]:
df.drop(['name'],axis=1,inplace=True)

In [20]:
df.head()

,selling_price,year,seller_type,owner,km_driven,ex_showroom_price,brand
2,150000,2018,1,0,12000,148114.0,11
3,65000,2015,1,0,23000,89643.0,16
5,18000,2010,1,0,60000,53857.0,6
6,78500,2018,1,0,17000,87719.0,6
9,50000,2016,1,0,42000,60122.0,2

In [21]:
X=df.drop('selling_price',axis=1)
y=df['selling_price']

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [24]:
from sklearn.preprocessing import StandardScaler

In [25]:
scaler=StandardScaler()

In [26]:
X_train_scaled=scaler.fit_transform(X_train)

In [27]:
X_test_scaled=scaler.transform(X_test)

In [28]:
X_train_scaled

array([[-0.5749005 ,  0.0776931 , -0.34757978,  0.13923465, -0.20319716,
        -0.24227585],
       [ 0.41859115,  0.0776931 ,  2.36788725, -0.56050753, -0.6635474 ,
        -0.24227585],
       [ 0.41859115,  0.0776931 , -0.34757978, -0.6604707 , -0.53841522,
        -0.24227585],
       ...,
       [-0.5749005 ,  0.0776931 , -0.34757978, -0.08568248, -0.512163  ,
        -0.24227585],
       [ 1.4120828 ,  0.0776931 , -0.34757978, -0.59799372,  0.36211088,
        -0.45554684],
       [-0.24373662,  0.0776931 , -0.34757978,  0.21420702, -0.61226874,
        -0.24227585]])

In [29]:
X_test_scaled

array([[ 7.49755031e-01,  7.76930969e-02, -3.47579780e-01,
         6.42622724e-02, -4.65191610e-01, -1.09535981e+00],
       [ 8.74272651e-02,  7.76930969e-02,  2.36788725e+00,
        -6.85461490e-01,  1.75495977e+00,  8.24079109e-01],
       [ 7.49755031e-01,  7.76930969e-02, -3.47579780e-01,
         6.42622724e-02, -6.12047422e-01, -4.55546837e-01],
       [-2.43736618e-01,  7.76930969e-02, -3.47579780e-01,
        -4.73039757e-01, -8.03973770e-02,  1.89043406e+00],
       [-9.06064384e-01,  7.76930969e-02, -3.47579780e-01,
        -8.56824800e-02, -6.12268745e-01, -2.42275846e-01],
       [-1.23722827e+00,  7.76930969e-02, -3.47579780e-01,
        -1.10673272e-01, -6.12268745e-01, -2.42275846e-01],
       [ 1.41208280e+00,  7.76930969e-02, -3.47579780e-01,
        -7.40441232e-01,  1.13349265e+01,  1.03735010e+00],
       [-2.23071992e+00,  7.76930969e-02, -3.47579780e-01,
         5.64078114e-01, -2.07595485e-02, -1.09535981e+00],
       [ 1.41208280e+00,  7.76930969e-02, -3.47579780e-01,
        -7.80426500e-01,  1.25591220e+00, -1.09535981e+00],
       [-2.43736618e-01,  7.76930969e-02, -3.47579780e-01,
         2.21979161e-01, -8.03973770e-02,  1.89043406e+00],
       [ 8.74272651e-02,  7.76930969e-02, -3.47579780e-01,
        -2.35627232e-01,  1.62100875e+00,  8.24079109e-01],
       [ 1.08091891e+00,  7.76930969e-02, -3.47579780e-01,
        -4.85535153e-01, -4.49222360e-01,  1.89043406e+00],
       [-1.56839215e+00,  7.76930969e-02,  2.36788725e+00,
         2.64188609e-01, -4.75270284e-01,  1.03735010e+00],
       [ 7.49755031e-01,  7.76930969e-02, -3.47579780e-01,
        -1.35664064e-01, -6.24969236e-01,  1.89043406e+00],
       [ 1.08091891e+00,  7.76930969e-02, -3.47579780e-01,
        -7.97920054e-01,  1.49301048e-01, -1.09535981e+00],
       [ 8.74272651e-02,  7.76930969e-02, -3.47579780e-01,
        -7.35443074e-01, -5.38415219e-01, -2.42275846e-01],
       [-1.56839215e+00,  7.76930969e-02, -3.47579780e-01,
         6.89032074e-01, -5.51149760e-01, -2.42275846e-01],
       [ 1.08091891e+00,  7.76930969e-02, -3.47579780e-01,
        -4.60544361e-01, -4.56406820e-01, -2.42275846e-01],
       [ 4.18591148e-01,  7.76930969e-02, -3.47579780e-01,
        -4.73039757e-01, -5.96639990e-01,  6.10808118e-01],
       [ 1.41208280e+00,  7.76930969e-02, -3.47579780e-01,
        -7.37942153e-01,  1.74838228e-01, -4.55546837e-01],
       [ 1.41208280e+00,  7.76930969e-02, -3.47579780e-01,
        -7.12951361e-01, -4.69890452e-01,  1.89043406e+00],
       [ 4.18591148e-01,  7.76930969e-02, -3.47579780e-01,
         1.89216233e-01,  1.38177937e-02,  1.89043406e+00],
       [ 1.41208280e+00,  7.76930969e-02, -3.47579780e-01,
        -7.22947678e-01, -4.88158048e-01, -2.42275846e-01],
       [-9.06064384e-01,  7.76930969e-02, -3.47579780e-01,
         1.42806882e-02, -5.99789576e-01, -2.42275846e-01],
       [-5.74900501e-01,  7.76930969e-02, -3.47579780e-01,
         6.89032074e-01, -6.26824937e-01, -4.55546837e-01],
       [-1.23722827e+00,  7.76930969e-02, -3.47579780e-01,
         8.63967619e-01, -1.27998681e-01,  1.89043406e+00],
       [ 7.49755031e-01,  7.76930969e-02, -3.47579780e-01,
        -4.35553569e-01, -5.66608266e-01,  1.89043406e+00],
       [ 4.18591148e-01,  7.76930969e-02, -3.47579780e-01,
        -6.10489113e-01,  3.01275396e-02,  1.89043406e+00],
       [-1.56839215e+00,  7.76930969e-02, -3.47579780e-01,
         1.16849806e+01, -5.82764789e-01, -1.52190179e+00],
       [ 8.74272651e-02,  7.76930969e-02, -3.47579780e-01,
        -3.60581193e-01, -5.38415219e-01, -2.42275846e-01],
       [-1.56839215e+00,  7.76930969e-02, -3.47579780e-01,
        -3.10599609e-01, -1.82648247e-01, -1.09535981e+00],
       [-2.89304768e+00,  7.76930969e-02, -3.47579780e-01,
         4.64114945e-01, -4.88294246e-01, -1.09535981e+00],
       [ 7.49755031e-01,  7.76930969e-02, -3.47579780e-01,
        -3.10599609e-01, -3.36041577e-01,  1.25062109e+00],
       [ 1.08091891e+00,  7.76930969e-02, -3.47579780e-01,
        -6.35479906e-01,  1.09480071e-01, -2.42275846e-01],
       [-2.43736618e-01,  7.76930969e-02, -3.47579780e-01,
        -5.60507529e-01, -6.12268745e-01, -2.42275846e-01],
       [-5.74900501e-01,  7.76930969e-02, -3.47579780e-01,
        -1.85645648e-01, -6.71651201e-01, -4.55546837e-01],
       [ 1.08091891e+00,  7.76930969e-02, -3.47579780e-01,
        -6.05490955e-01,  7.90795018e-01,  1.89043406e+00],
       [ 8.74272651e-02,  7.76930969e-02, -3.47579780e-01,
        -3.60581193e-01, -4.97640854e-01, -4.55546837e-01],
       [ 7.49755031e-01,  7.76930969e-02, -3.47579780e-01,
        -3.60581193e-01, -4.98917713e-01, -4.55546837e-01],
       [-5.74900501e-01,  7.76930969e-02, -3.47579780e-01,
         1.06389396e+00, -1.28202979e-01, -4.55546837e-01],
       [-1.23722827e+00,  7.76930969e-02, -3.47579780e-01,
         4.89105738e-01, -5.43624804e-01, -1.09535981e+00],
       [-2.43736618e-01,  7.76930969e-02, -3.47579780e-01,
         1.18884792e+00, -1.00112080e-01, -4.55546837e-01],
       [ 4.18591148e-01,  7.76930969e-02, -3.47579780e-01,
        -4.10562777e-01, -3.37835104e-02,  1.03735010e+00],
       [-1.56839215e+00,  7.76930969e-02,  2.36788725e+00,
        -1.60654856e-01, -1.91194690e-01, -1.09535981e+00],
       [ 8.74272651e-02,  7.76930969e-02, -3.47579780e-01,
         6.42622724e-02, -4.93537881e-01, -2.42275846e-01],
       [ 7.49755031e-01,  7.76930969e-02, -3.47579780e-01,
        -2.98104213e-01, -2.07595485e-02, -1.09535981e+00],
       [ 7.49755031e-01,  7.76930969e-02, -3.47579780e-01,
        -4.45549886e-01, -5.40628441e-01, -4.55546837e-01],
       [-9.06064384e-01,  7.76930969e-02, -3.47579780e-01,
         1.39234649e-01, -6.12268745e-01, -2.42275846e-01],
       [-5.74900501e-01,  7.76930969e-02,  2.36788725e+00,
        -5.10525945e-01,  2.02896240e+01, -6.68817828e-01],
       [ 7.49755031e-01,  7.76930969e-02, -3.47579780e-01,
         1.39234649e-01,  2.23472120e-02, -2.42275846e-01],
       [ 1.41208280e+00,  7.76930969e-02, -3.47579780e-01,
        -7.22947678e-01,  1.49301048e-01, -1.09535981e+00],
       [ 7.49755031e-01,  7.76930969e-02, -3.47579780e-01,
        -6.06916880e-02, -9.86649733e-02, -1.09535981e+00],
       [-1.56839215e+00,  7.76930969e-02,  2.36788725e+00,
         3.14170193e-01,  5.39611312e-01,  1.89043406e+00],
       [ 4.18591148e-01,  7.76930969e-02, -3.47579780e-01,
         1.14243857e-01, -1.27998681e-01,  1.89043406e+00],
       [ 4.18591148e-01,  7.76930969e-02, -3.47579780e-01,
        -4.35553569e-01, -1.28202979e-01, -4.55546837e-01],
       [ 4.18591148e-01,  7.76930969e-02, -3.47579780e-01,
         4.64114945e-01, -5.38415219e-01, -2.42275846e-01],
       [-2.43736618e-01,  7.76930969e-02,  2.36788725e+00,
         4.64114945e-01,  8.74440725e-03, -4.55546837e-01],
       [-1.89955603e+00,  7.76930969e-02, -3.47579780e-01,
         5.14096530e-01, -4.80616067e-01, -2.42275846e-01],
       [-1.23722827e+00,  7.76930969e-02, -3.47579780e-01,
         1.32587098e-01, -7.06092345e-01, -1.09535981e+00],
       [-1.89955603e+00,  7.76930969e-02,  2.36788725e+00,
        -1.60654856e-01, -1.27998681e-01,  1.89043406e+00],
       [ 1.41208280e+00,  7.76930969e-02, -3.47579780e-01,
        -7.02955044e-01, -5.99789576e-01, -2.42275846e-01],
       [ 1.08091891e+00,  7.76930969e-02, -3.47579780e-01,
        -6.65118985e-01,  1.05355558e+00,  8.24079109e-01],
       [-2.43736618e-01,  7.76930969e-02, -3.47579780e-01,
        -4.60544361e-01, -5.89574704e-01, -4.55546837e-01],
       [ 7.49755031e-01,  7.76930969e-02, -3.47579780e-01,
        -4.60544361e-01, -5.48715215e-01, -4.55546837e-01],
       [ 1.08091891e+00,  7.76930969e-02, -3.47579780e-01,
        -4.60544361e-01, -5.48715215e-01, -4.55546837e-01],
       [ 1.08091891e+00,  7.76930969e-02, -3.47579780e-01,
        -4.35553569e-01, -5.40628441e-01, -4.55546837e-01],
       [-9.06064384e-01,  7.76930969e-02, -3.47579780e-01,
         1.16849806e+01, -6.12268745e-01, -2.42275846e-01],
       [ 8.74272651e-02,  7.76930969e-02, -3.47579780e-01,
        -7.12726444e-01, -1.41822808e-01,  1.67716307e+00],
       [ 1.08091891e+00,  7.76930969e-02, -3.47579780e-01,
        -5.92995559e-01,  1.08566433e+00,  8.24079109e-01],
       [-5.74900501e-01,  7.76930969e-02, -3.47579780e-01,
        -1.08499073e-01, -3.86349822e-01, -2.42275846e-01],
       [-9.06064384e-01,  7.76930969e-02, -3.47579780e-01,
        -2.60618025e-01,  5.57844859e-01,  1.89043406e+00],
       [ 4.18591148e-01,  7.76930969e-02, -3.47579780e-01,
        -4.10562777e-01,  1.97623093e+00, -2.42275846e-01],
       [-5.74900501e-01,  7.76930969e-02, -3.47579780e-01,
        -1.60654856e-01,  8.74440725e-03, -4.55546837e-01],
       [ 8.74272651e-02,  7.76930969e-02,  2.36788725e+00,
        -1.85645648e-01,  1.62100875e+00,  8.24079109e-01],
       [ 8.74272651e-02,  7.76930969e-02, -3.47579780e-01,
        -6.75465173e-01,  1.76665580e+00,  8.24079109e-01],
       [ 7.49755031e-01,  7.76930969e-02,  2.36788725e+00,
        -4.80536995e-01,  2.23472120e-02, -2.42275846e-01],
       [ 1.08091891e+00,  7.76930969e-02, -3.47579780e-01,
        -7.85424658e-01, -5.31690428e-01, -4.55546837e-01],
       [ 1.08091891e+00,  7.76930969e-02, -3.47579780e-01,
        -6.57971618e-01,  1.05355558e+00,  8.24079109e-01],
       [ 8.74272651e-02,  7.76930969e-02, -3.47579780e-01,
        -2.10636440e-01, -1.15740835e-01,  1.89043406e+00],
       [ 4.18591148e-01,  7.76930969e-02, -3.47579780e-01,
         6.89032074e-01, -5.38415219e-01, -2.42275846e-01],
       [ 1.41208280e+00,  7.76930969e-02, -3.47579780e-01,
        -4.85535153e-01, -4.49222360e-01,  1.89043406e+00],
       [ 1.41208280e+00,  7.76930969e-02, -3.47579780e-01,
        -7.47938470e-01,  8.07819805e-01,  1.89043406e+00],
       [ 7.49755031e-01,  7.76930969e-02, -3.47579780e-01,
         4.89105738e-01, -1.47866607e-01, -2.42275846e-01],
       [-1.23722827e+00,  7.76930969e-02, -3.47579780e-01,
        -4.23058173e-01, -2.51859930e-02,  1.89043406e+00],
       [ 4.18591148e-01,  7.76930969e-02,  2.36788725e+00,
        -2.33203126e-01, -9.86649733e-02, -1.09535981e+00],
       [-2.43736618e-01,  7.76930969e-02, -3.47579780e-01,
        -6.72966094e-01, -5.49963949e-02,  1.89043406e+00],
       [ 4.18591148e-01,  7.76930969e-02, -3.47579780e-01,
         1.14243857e-01, -5.40202822e-01,  1.89043406e+00],
       [ 7.49755031e-01,  7.76930969e-02, -3.47579780e-01,
        -3.60581193e-01, -7.20211818e-02,  1.89043406e+00],
       [ 1.41208280e+00,  7.76930969e-02, -3.47579780e-01,
        -5.60507529e-01,  8.07819805e-01,  1.89043406e+00],
       [-2.43736618e-01,  7.76930969e-02, -3.47579780e-01,
        -4.60544361e-01, -3.68439747e-01, -1.09535981e+00],
       [ 1.08091891e+00,  7.76930969e-02, -3.47579780e-01,
        -6.32730918e-01, -5.12162998e-01, -2.42275846e-01],
       [ 8.74272651e-02,  7.76930969e-02, -3.47579780e-01,
        -9.66034562e-02, -2.07595485e-02, -1.09535981e+00],
       [-1.23722827e+00,  7.76930969e-02, -3.47579780e-01,
         6.14059698e-01, -4.44489470e-01, -1.09535981e+00],
       [-1.23722827e+00,  7.76930969e-02, -3.47579780e-01,
         1.23882950e+00, -1.15740835e-01,  1.89043406e+00],
       [-5.74900501e-01,  7.76930969e-02, -3.47579780e-01,
        -1.60654856e-01, -6.67343930e-01, -1.09535981e+00],
       [ 1.08091891e+00,  7.76930969e-02, -3.47579780e-01,
        -4.35553569e-01, -3.68439747e-01, -1.09535981e+00],
       [ 1.08091891e+00,  7.76930969e-02, -3.47579780e-01,
        -6.35479906e-01, -1.63410238e-01,  1.03735010e+00],
       [-9.06064384e-01,  7.76930969e-02, -3.47579780e-01,
         4.39124153e-01, -5.43624804e-01, -1.09535981e+00],
       [ 4.18591148e-01,  7.76930969e-02, -3.47579780e-01,
         6.42622724e-02, -2.07595485e-02, -1.09535981e+00],
       [ 4.18591148e-01,  7.76930969e-02, -3.47579780e-01,
        -3.60581193e-01, -3.15101089e-01, -4.55546837e-01],
       [ 1.08091891e+00,  7.76930969e-02, -3.47579780e-01,
        -6.60470698e-01, -5.38840839e-01, -4.55546837e-01],
       [-2.43736618e-01,  7.76930969e-02, -3.47579780e-01,
         1.89216233e-01, -6.64722113e-01, -1.09535981e+00],
       [ 1.08091891e+00,  7.76930969e-02, -3.47579780e-01,
        -6.60470698e-01, -4.44489470e-01, -1.09535981e+00],
       [ 1.08091891e+00,  7.76930969e-02, -3.47579780e-01,
        -1.60654856e-01, -2.07595485e-02, -1.09535981e+00],
       [-1.23722827e+00,  7.76930969e-02, -3.47579780e-01,
         1.89216233e-01, -4.75270284e-01,  1.03735010e+00],
       [ 4.18591148e-01,  7.76930969e-02, -3.47579780e-01,
        -1.85645648e-01,  3.28685303e-02, -2.42275846e-01],
       [ 7.49755031e-01,  7.76930969e-02, -3.47579780e-01,
        -3.10599609e-01, -5.81800301e-02,  1.03735010e+00],
       [-1.56839215e+00,  7.76930969e-02, -3.47579780e-01,
         4.39124153e-01, -6.12268745e-01, -2.42275846e-01],
       [-1.56839215e+00,  7.76930969e-02, -3.47579780e-01,
         9.13949203e-01, -2.03197165e-01, -2.42275846e-01],
       [-5.74900501e-01,  7.76930969e-02, -3.47579780e-01,
         1.39234649e-01, -7.90583434e-03, -4.55546837e-01],
       [ 4.18591148e-01,  7.76930969e-02, -3.47579780e-01,
         6.42622724e-02, -3.50785043e-01, -1.09535981e+00],
       [-5.74900501e-01,  7.76930969e-02, -3.47579780e-01,
         5.39087322e-01, -2.03197165e-01, -2.42275846e-01],
       [-9.06064384e-01,  7.76930969e-02, -3.47579780e-01,
         1.31380188e+00, -7.38388366e-01, -1.09535981e+00],
       [ 1.08091891e+00,  7.76930969e-02,  2.36788725e+00,
        -7.07953203e-01,  9.61042887e-01,  1.89043406e+00],
       [ 1.41208280e+00,  7.76930969e-02, -3.47579780e-01,
        -7.10452282e-01, -5.99789576e-01, -2.42275846e-01],
       [ 8.74272651e-02,  7.76930969e-02, -3.47579780e-01,
         5.42909463e-02,  1.40031644e+00,  8.24079109e-01],
       [-5.74900501e-01,  7.76930969e-02, -3.47579780e-01,
        -2.10636440e-01,  1.49301048e-01, -1.09535981e+00],
       [ 1.41208280e+00,  7.76930969e-02, -3.47579780e-01,
        -7.85424658e-01, -5.21475556e-01, -4.55546837e-01],
       [ 1.41208280e+00,  7.76930969e-02, -3.47579780e-01,
        -4.35553569e-01, -5.82764789e-01,  1.25062109e+00],
       [ 4.18591148e-01,  7.76930969e-02, -3.47579780e-01,
        -6.10489113e-01,  5.39611312e-01,  1.89043406e+00],
       [ 8.74272651e-02,  7.76930969e-02, -3.47579780e-01,
        -3.10599609e-01, -5.38415219e-01, -2.42275846e-01],
       [ 1.08091891e+00,  7.76930969e-02, -3.47579780e-01,
        -6.60470698e-01,  9.61042887e-01,  1.89043406e+00],
       [ 7.49755031e-01,  7.76930969e-02, -3.47579780e-01,
        -1.85645648e-01,  1.62100875e+00,  8.24079109e-01],
       [ 1.08091891e+00,  7.76930969e-02, -3.47579780e-01,
         4.39124153e-01, -6.50863936e-01, -4.55546837e-01],
       [ 4.18591148e-01,  7.76930969e-02, -3.47579780e-01,
        -1.35664064e-01, -2.03197165e-01, -2.42275846e-01],
       [-1.23722827e+00,  7.76930969e-02, -3.47579780e-01,
         1.06389396e+00, -4.19326835e-01, -4.55546837e-01]])

In [30]:
df.head()

,selling_price,year,seller_type,owner,km_driven,ex_showroom_price,brand
2,150000,2018,1,0,12000,148114.0,11
3,65000,2015,1,0,23000,89643.0,16
5,18000,2010,1,0,60000,53857.0,6
6,78500,2018,1,0,17000,87719.0,6
9,50000,2016,1,0,42000,60122.0,2

In [31]:
from xgboost import XGBRegressor
from sklearn.metrics import r2_score,mean_absolute_error

In [32]:
xgb_model=XGBRegressor(n_estimators=100,learning_rate=0.1,max_depth=5,random_state=42)

In [33]:
xgb_model.fit(X_train_scaled,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [34]:
y_pred=xgb_model.predict(X_test_scaled)

In [35]:
y_pred

array([ 39271.61 , 159942.25 ,  32154.994,  51414.477,  26321.164,
        22961.967, 405793.88 ,  24426.094, 166777.66 ,  45422.14 ,
       135456.3  ,  50414.965,  19388.906,  41412.914,  89411.67 ,
        43775.95 ,  20618.934,  50171.887,  36055.363,  94704.766,
        61497.234,  69378.06 ,  60605.836,  23177.168,  31713.266,
        30193.174,  36338.17 ,  72388.836,  23901.244,  37900.887,
        31942.574,  16043.892,  49649.383,  87248.95 ,  35104.117,
        25806.84 , 120149.45 ,  35577.934,  41405.438,  35072.438,
        22146.957,  43163.32 ,  60210.484,  31462.707,  34476.55 ,
        64725.23 ,  38345.39 ,  22469.604, 367998.66 ,  67103.82 ,
        88898.79 ,  59184.7  ,  54724.645,  49830.53 ,  53954.32 ,
        39531.566,  41818.742,  18372.139,  24352.336,  29466.938,
        50796.88 , 136252.11 ,  33921.613,  37482.992,  47111.305,
        47374.273,  24981.758,  50972.04 , 134728.44 ,  32801.734,
        57723.34 , 141369.56 ,  41563.777, 141251.05 , 137605.8  ,
        62760.902,  57379.605, 136436.06 ,  48103.887,  39288.07 ,
        55365.234, 156466.16 ,  55760.59 ,  36453.21 ,  53039.18 ,
        48636.656,  41729.254,  61642.895, 120149.45 ,  37870.402,
        48619.082,  49381.953,  21707.479,  33256.777,  23240.764,
        50581.344,  66456.48 ,  24580.799,  58312.656,  47233.14 ,
        57528.855,  24649.19 ,  54502.324,  66685.39 ,  20146.291,
        64108.49 ,  59726.12 ,  20670.86 ,  33191.41 ,  40145.312,
        42740.96 ,  40457.95 ,  26016.9  , 143895.66 ,  50796.88 ,
       124580.15 ,  44418.5  ,  62329.875,  45853.914,  80371.4  ,
        37098.055, 115749.375, 138594.19 ,  45551.234,  54374.598,
        25388.195], dtype=float32)

In [36]:
y_test

816      45000
890     185000
392      45000
386      35000
878      35000
         ...
627     120000
409     140000
1041     30000
352      50000
722      15000
Name: selling_price, Length: 126, dtype: int64

In [37]:
r2=r2_score(y_test,y_pred)

In [38]:
r2

0.7410446405410767

In [39]:
mae=mean_absolute_error(y_test,y_pred)

In [40]:
mae

14679.923828125

In [42]:
import pickle
pickle.dump(xgb_model, open('bike_model.pkl','wb'))
pickle.dump(scaler, open('scaler.pkl','wb'))